# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('current', 'current')], max_length=7)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
