# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integer',
            name='key',
            field=models.CharField(choices=[('current', 'current')], default='current', max_length=7),
        ),
    ]
